development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("redis://default:bWriPV6i2cfIENkKCr6ZAplpPgCtYla6@redis-16526.c242.eu-west-1-2.ec2.cloud.redislabs.com:16526") { "redis://localhost:6379/1" } %>
  channel_prefix: swapt_production
